### ISSUE TITLE
Connection terminated unexpectedly

### ISSUE THREAD

**Issue by tienlatien252** [tienlatien252/Nursing-Test#75]
This seem to be the connection with Postgresql database lost when the backend is idle for a while.

https://github.com/brianc/node-postgres/issues/1611#issuecomment-384011112

https://github.com/brianc/node-postgres/issues/1611#issuecomment-558566873

Done:

- Test with "npm start"
- Test with docker
- Apply the fix
- Test again

**Comment by tienlatien252** [comment]
Error

```
events.js:292
throw er; // Unhandled 'error' event
^
Error: Connection terminated unexpectedly
at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:123:73)
at Object.onceWrapper (events.js:421:28)
at Connection.emit (events.js:315:20)
at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:102:12)
at Socket.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Client instance at:
at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:310:10)
at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:140:16)
at Object.onceWrapper (events.js:421:28)
[... lines matching original stack trace ...]
at processTicksAndRejections (internal/process/task_queues.js:84:21)
[nodemon] app crashed - waiting for file changes before starting...
```
